#
# Base site config.
#

title: "Darrell D.E. Long"
author: "Darrell D.E. Long"
email: "darrell@ucsc.edu"
description: "A work in progress."
show_excerpts: true


#
# Site specific config.
#
darrell:
  name: "Darrell Long"
  date_format: "%b %Y"
  portrait: "assets/portrait.png"
  html_lang: "en"
  links:
    github:  "darrelllong"
    linkedin: "in/darrell-d-e-long"
    wikipedia: "Darrell_Long"

  navigation:
    - title: "About"
      url: "/"
    - title: "Curriculum Vitae"
      url: "/"
    - title: "Publications"
      url: "/publications"
    - title: "Laboratory"
      url: "https://www.ssrc.ucsc.edu/index.html"
    - title: "Citations"
      url: "https://scholar.google.com/citations?user=PqdLgQ0AAAAJ&hl=en&oi=ao"


#
# Custom collections (papers, articles, etc.).
#
collections:
  publications:
    output: true
    permalink: "/publications/:path"


#
# No man's land.
#

# Sass (for the UI and whatnot, modifed from the plainwhite gem theme).
sass:
  sass_dir: _sass
