#
# Base site config.
#
title: "Darrell D.E. Long"
author: "Darrell D.E. Long"
email: "darrell@ucsc.edu"
description: "A work in progress."
show_excerpts: true


#
# Site specific config.
#
darrell:
  name: "Darrell Long"
  date_format: "%B %Y"
  portrait: "assets/images/portrait.png"
  html_lang: "en"
  links:
    github: "https://github.com/darrelllong"
    linkedin: "https://www.linkedin.com/in/darrell-d-e-long/"
    wikipedia: "https://en.wikipedia.org/wiki/Darrell_Long"
    gscholar: "https://scholar.google.com/citations?user=PqdLgQ0AAAAJ&hl=en&oi=ao"
    orcid: "https://orcid.org/0000-0002-0822-0740"

  navigation:
    - title: "About"
      url: "/"
    - title: "Curriculum Vitae"
      url: "/cv.pdf"
    - title: "Publications"
      url: "/publications.html"
    - title: "Laboratory"
      url: "https://www.ssrc.ucsc.edu/index.html"
    - title: "Students"
      url: "https://www.genealogy.math.ndsu.nodak.edu/id.php?id=10794"


#
# Custom collections (publications, articles, etc.).
#
collections:
  publications:
    output: true
    permalink: "/publications/:path"


#
# No man's land.
#
sass:
  sass_dir: _sass
