#
# Base site config.
#

title: "Darrell D.E. Long"
author: "Darrell D.E. Long"
email: "darrell@ucsc.edu"
description: "A work in progress."
show_excerpts: true


#
# Site specific config.
#
darrell:
  name: "Darrell Long"
  date_format: "%b %Y"
  search: true
  sitemap: true
  portrait: "assets/portfolio.png"
  html_lang: "en"
  links:
    github:  "darrelllong"
    linkedin: "in/darrell-d-e-long"
    wikipedia: "Darrell_Long"

  navigation:
    - title: "About"
      url: "/"
    - title: "Papers"
      url: "/papers"
    - title: "Laboratories"
      url: "/labs"
    - title: "CV"
      url: "/cv"


#
# Custom collections (papers, articles, etc.).
#
collections:
  papers:
    output: true
    permalink: "/papers/:path"


#
# No man's land.
#

# Sass (for the UI and whatnot, modifed from the plainwhite gem theme).
sass:
  sass_dir: _sass
